name: mains
description: "A new Flutter project."
publish_to: 'none' 


version: 1.0.2+5

environment:
  sdk: '>=3.7.0 <4.0.0'


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons:
  google_fonts:
  dio:
  video_thumbnail: ^0.5.6
  youtube_player_flutter: ^9.0.0
  percent_indicator: 
  web_socket_channel:
  slide_to_act: ^2.0.2
  share_plus:
  carousel_slider:
  flutter_otp_text_field:
  loading_animation_widget:
  youtube_player_iframe:
  package_info_plus:
  pinput:
  flutter_tts: ^3.8.5
  gif: ^2.3.0
  flutter_image_compress:
  syncfusion_flutter_charts:
  photo_view:
  image_picker: ^1.0.7
  flutter_reorderable_grid_view:
  syncfusion_flutter_gauges:
  mobile_scanner: ^3.5.6
  flutter_spinkit:
  just_audio:
  audio_session:
  device_info_plus:
  fluttertoast:
  upgrader: ^11.5.0
  sqflite:
  path_provider:
  shared_preferences:
  speech_to_text:
  path:
  camera:
  get:
  fl_chart:
  video_player:
  chewie:
  http:
  audioplayers:
  url_launcher:
  flutter_rating_bar:
  flutter_animate:
  image_painter:
  image_painter_hap:
  webview_flutter: ^4.13.0
  lottie:
  flutter_launcher_icons:
  intl:
  confetti:
  exif:
  image:
  cached_network_image:
  syncfusion_flutter_pdfviewer: ^31.1.19
  pdf: ^3.10.7

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/images/mains-logo.png"
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/mains-logo.png"
  min_sdk_android: 21 

  
dependency_overrides:
  flutter_inappwebview: ^6.1.5
dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/
    - assets/lottie/
    - assets/gif/
